### PR TITLE
Feature/create migrations

### LINKED ISSUE #19: Prepare database migration files

### PR DESCRIPTION
**Pull request by osueke-christian**
## Description
Migration files for the project based on the understanding of its features so far. 

Dependencies: None.

Fixes #19 

## How Has This Been Tested?
Ran *php artisan migrate* to confirm migrations ran successfully.

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by darlingtim** [comment]
The migrations are really awesome  but  we will need to modify the teachers migration after merging this pull request.

**Review by darlingtim — APPROVED** [review]
The migrations are really awesome but we will need to modify the teachers migration after merging this pull request.

**Comment by Niyiojeyinka** [comment]
welldone

**Comment by chifum** [comment]
Great Job

**Pull request merged**
